#!/bin/sh
set -o errexit

echo -e "\n========================================================"

printf '%s\n' \
     "[fs]" \
     "storage-url: ${S3QL_STORAGE_URL}/${S3QL_PREFIX}" \
     "backend-login: ${S3QL_BACKEND_LOGIN}" \
     "backend-password: ${S3QL_BACKEND_PASSWORD}" \
     "fs-passphrase: ${S3QL_FS_PASSPHRASE}" \
     > "${S3QL_AUTHINFO_FILE}"

chmod 0600 ${S3QL_AUTHINFO_FILE}

printf '%s\n' "${S3QL_CRONTAB}" > /etc/crontab

# On first run ...
if [ ! -e /s3ql-fs-created ]; then
    touch /s3ql-fs-created

    s3ql makefs
fi

echo -e "\n========================================================"
# Display OS version and S3QL version in log
echo      "VERSIONS:"
echo -e   "Alpine \c" && cat /etc/alpine-release
echo      $(mount.s3ql --version)
echo -e   "========================================================\n"

# When container is stopped, unmount s3ql cleanly.
term_handler() {
    s3ql unmount
}

trap 'term_handler' SIGTERM

# Mount s3ql filesystem and wait.
supercronic /etc/crontab &
s3ql mount &
wait ${!}
